# Generated by Django 6.0.6 on 2026-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='other_service',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
